python tools/run_net.py --cfg /home/ubuntu/RoiSlowFast/configs/EPIC-KITCHENS/SLOWFAST_8x8_R50.yaml NUM_GPUS 1 OUTPUT_DIR /home/ubuntu/results EPICKITCHENS.VISUAL_DATA_DIR /home/ubuntu/data EPICKITCHENS.ANNOTATIONS_DIR /home/ubuntu/data/annotations TRAIN.ENABLE False TEST.ENABLE True TEST.CHECKPOINT_FILE_PATH /home/ubuntu/RoiSlowFast/checkpoints/SlowFast.pyth EPICKITCHENS.PARTICIPANT_ID 10 EPICKITCHENS.TEST_LIST /home/ubuntu/data/annotations/annotations_P10.pkl
python tools/run_net.py --cfg /home/ubuntu/RoiSlowFast/configs/EPIC-KITCHENS/SLOWFAST_8x8_R50.yaml NUM_GPUS 1 OUTPUT_DIR /home/ubuntu/results EPICKITCHENS.VISUAL_DATA_DIR /home/ubuntu/data EPICKITCHENS.ANNOTATIONS_DIR /home/ubuntu/data/annotations TRAIN.ENABLE False TEST.ENABLE True TEST.CHECKPOINT_FILE_PATH /home/ubuntu/RoiSlowFast/checkpoints/SlowFast.pyth EPICKITCHENS.PARTICIPANT_ID 16 EPICKITCHENS.TEST_LIST /home/ubuntu/data/annotations/annotations_P16.pkl
python tools/run_net.py --cfg /home/ubuntu/RoiSlowFast/configs/EPIC-KITCHENS/SLOWFAST_8x8_R50.yaml NUM_GPUS 1 OUTPUT_DIR /home/ubuntu/results EPICKITCHENS.VISUAL_DATA_DIR /home/ubuntu/data EPICKITCHENS.ANNOTATIONS_DIR /home/ubuntu/data/annotations TRAIN.ENABLE False TEST.ENABLE True TEST.CHECKPOINT_FILE_PATH /home/ubuntu/RoiSlowFast/checkpoints/SlowFast.pyth EPICKITCHENS.PARTICIPANT_ID 18 EPICKITCHENS.TEST_LIST /home/ubuntu/data/annotations/annotations_P18.pkl
python tools/run_net.py --cfg /home/ubuntu/RoiSlowFast/configs/EPIC-KITCHENS/SLOWFAST_8x8_R50.yaml NUM_GPUS 1 OUTPUT_DIR /home/ubuntu/results EPICKITCHENS.VISUAL_DATA_DIR /home/ubuntu/data EPICKITCHENS.ANNOTATIONS_DIR /home/ubuntu/data/annotations TRAIN.ENABLE False TEST.ENABLE True TEST.CHECKPOINT_FILE_PATH /home/ubuntu/RoiSlowFast/checkpoints/SlowFast.pyth EPICKITCHENS.PARTICIPANT_ID 20 EPICKITCHENS.TEST_LIST /home/ubuntu/data/annotations/annotations_P20.pkl
python tools/run_net.py --cfg /home/ubuntu/RoiSlowFast/configs/EPIC-KITCHENS/SLOWFAST_8x8_R50.yaml NUM_GPUS 1 OUTPUT_DIR /home/ubuntu/results EPICKITCHENS.VISUAL_DATA_DIR /home/ubuntu/data EPICKITCHENS.ANNOTATIONS_DIR /home/ubuntu/data/annotations TRAIN.ENABLE False TEST.ENABLE True TEST.CHECKPOINT_FILE_PATH /home/ubuntu/RoiSlowFast/checkpoints/SlowFast.pyth EPICKITCHENS.PARTICIPANT_ID 30 EPICKITCHENS.TEST_LIST /home/ubuntu/data/annotations/annotations_P30.pkl



python tools/run_net.py --cfg configs/EPIC-KITCHENS/SLOWFAST_8x8_R50.yaml NUM_GPUS num_gpus 
OUTPUT_DIR /path/to/experiment_dir EPICKITCHENS.VISUAL_DATA_DIR /path/to/dataset 
EPICKITCHENS.ANNOTATIONS_DIR /path/to/annotations TRAIN.ENABLE False TEST.ENABLE True 
TEST.CHECKPOINT_FILE_PATH /path/to/experiment_dir/checkpoints/checkpoint_best.pyth 
EPICKITCHENS.TEST_LIST EPIC_100_test_timestamps.pkl EPICKITCHENS.TEST_SPLIT test

python tools/run_net.py --cfg configs/EPIC-KITCHENS/SLOWFAST_8x8_R50.yaml NUM_GPUS num_gpus 
OUTPUT_DIR /path/to/experiment_dir EPICKITCHENS.VISUAL_DATA_DIR /path/to/dataset 
EPICKITCHENS.ANNOTATIONS_DIR /path/to/annotations TRAIN.ENABLE False TEST.ENABLE True 
TEST.CHECKPOINT_FILE_PATH /path/to/experiment_dir/checkpoints/checkpoint_best.pyth

python tools/run_net.py --cfg /home/ubuntu/RoiSlowFast/configs/EPIC-KITCHENS/SLOWFAST_8x8_R50.yaml NUM_GPUS 1 OUTPUT_DIR /home/ubuntu/results EPICKITCHENS.VISUAL_DATA_DIR /home/ubuntu/data EPICKITCHENS.ANNOTATIONS_DIR /home/ubuntu/data/annotations TRAIN.ENABLE False TEST.ENABLE True TEST.CHECKPOINT_FILE_PATH /home/ubuntu/RoiSlowFast/checkpoints/SlowFast.pyth EPICKITCHENS.PARTICIPANT_ID 16 EPICKITCHENS.TEST_LIST /home/ubuntu/data/annotations/annotations_P16.pkl EPICKITCHENS.TEST_SPLIT test
python tools/run_net.py --cfg /home/ubuntu/RoiSlowFast/configs/EPIC-KITCHENS/SLOWFAST_8x8_R50.yaml NUM_GPUS 1 OUTPUT_DIR /home/ubuntu/results EPICKITCHENS.VISUAL_DATA_DIR /home/ubuntu/data EPICKITCHENS.ANNOTATIONS_DIR /home/ubuntu/data/annotations TRAIN.ENABLE False TEST.ENABLE True TEST.CHECKPOINT_FILE_PATH /home/ubuntu/RoiSlowFast/checkpoints/SlowFast.pyth EPICKITCHENS.PARTICIPANT_ID 18 EPICKITCHENS.TEST_LIST /home/ubuntu/data/annotations/annotations_P18.pkl EPICKITCHENS.TEST_SPLIT test
python tools/run_net.py --cfg /home/ubuntu/RoiSlowFast/configs/EPIC-KITCHENS/SLOWFAST_8x8_R50.yaml NUM_GPUS 1 OUTPUT_DIR /home/ubuntu/results EPICKITCHENS.VISUAL_DATA_DIR /home/ubuntu/data EPICKITCHENS.ANNOTATIONS_DIR /home/ubuntu/data/annotations TRAIN.ENABLE False TEST.ENABLE True TEST.CHECKPOINT_FILE_PATH /home/ubuntu/RoiSlowFast/checkpoints/SlowFast.pyth EPICKITCHENS.PARTICIPANT_ID 10 EPICKITCHENS.TEST_LIST /home/ubuntu/data/annotations/annotations_P10.pkl EPICKITCHENS.TEST_SPLIT test
python tools/run_net.py --cfg /home/ubuntu/RoiSlowFast/configs/EPIC-KITCHENS/SLOWFAST_8x8_R50.yaml NUM_GPUS 1 OUTPUT_DIR /home/ubuntu/results EPICKITCHENS.VISUAL_DATA_DIR /home/ubuntu/data EPICKITCHENS.ANNOTATIONS_DIR /home/ubuntu/data/annotations TRAIN.ENABLE False TEST.ENABLE True TEST.CHECKPOINT_FILE_PATH /home/ubuntu/RoiSlowFast/checkpoints/SlowFast.pyth EPICKITCHENS.PARTICIPANT_ID 20 EPICKITCHENS.TEST_LIST /home/ubuntu/data/annotations/annotations_P20.pkl EPICKITCHENS.TEST_SPLIT test
python tools/run_net.py --cfg /home/ubuntu/RoiSlowFast/configs/EPIC-KITCHENS/SLOWFAST_8x8_R50.yaml NUM_GPUS 1 OUTPUT_DIR /home/ubuntu/results EPICKITCHENS.VISUAL_DATA_DIR /home/ubuntu/data EPICKITCHENS.ANNOTATIONS_DIR /home/ubuntu/data/annotations TRAIN.ENABLE False TEST.ENABLE True TEST.CHECKPOINT_FILE_PATH /home/ubuntu/RoiSlowFast/checkpoints/SlowFast.pyth EPICKITCHENS.PARTICIPANT_ID 30 EPICKITCHENS.TEST_LIST /home/ubuntu/data/annotations/annotations_P30.pkl EPICKITCHENS.TEST_SPLIT test

16: json_stats: {"noun_top1_acc": "28.07", "noun_top5_acc": "64.91", "split": "test_final", "verb_top1_acc": "49.12", "verb_top5_acc": "87.72"}
18: json_stats: {"noun_top1_acc": "40.87", "noun_top5_acc": "66.71", "split": "test_final", "verb_top1_acc": "51.15", "verb_top_5_acc": "86.87"}
10: json_stats: {"noun_top1_acc": "28.51", "noun_top5_acc": "60.43", "split": "test_final", "verb_top1_acc": "60.43", "verb_to$5_acc": "85.96"}
20: json_stats: {"noun_top1_acc": "56.31", "noun_top5_acc": "81.98", "split": "test_final", "verb_top1_acc": "77.48", "verb_top5_acc": "96.85"}
30: json_stats: {"noun_top1_acc": "54.04", "noun_top5_acc": "80.23", "split": "test_final", "verb_top1_acc": "66.72", "verb_top5_acc": "92.75"}
